### ISSUE TITLE
As a developer, I want to add comprehensive test cases , so that functionality is thoroughly validated and meet the requirements described in the issue

### ISSUE THREAD

**Issue by OmarSemou** [ITU-BDSA2024-GROUP18/Chirp#107]
As a developer, I want to add comprehensive test cases for the "Forget me!" feature among others, so that its functionality is thoroughly validated and the feature meets the requirements described in the issue.

**Acceptance Criteria:**

- Unit tests are created to cover the following scenarios:
  -  The "Forget me!" button is displayed correctly on the user information page.
   - Clicking the button triggers the deletion logic
   - The user is logged out of the Chirp! application after clicking the button.
   - All personal data (e.g., name, email, links to other users) is deleted or appropriately.
- Integration tests are created to verify:
   - End-to-end functionality of the "Forget me!" feature.
  - The system handles edge cases, such as when the user is already logged out or does not exist.
- All test cases are successfully executed in the CI/CD pipeline.

**Definition of Done:**

- Unit tests and integration tests are implemented and reviewed by peers.
- Unit tests cover all methods in Core and Infrastructure.
- All test cases pass in local and CI/CD environments.
- Documentation or comments for the tests are added where necessary.

**Comment by Asger124** [comment]
Reopened this at it was accidently linked to a wrong PR
