### ISSUE TITLE
Must Have: FIGURE OUT WHAT TO DO ABOUT HELGE AND ADRIAN USERS LOGIN -- SEE DESCRIPTION

### ISSUE THREAD

**Issue by Asger124** [ITU-BDSA2024-GROUP18/Chirp#123]
In session 08 we were given this requirement: 

_please make sure that two users, Helge and Adrian respectively can login to your Chirp! applications. They should be able to do so using their email addresses (ropf@itu.dk and adho@itu.dk respectively). Helge wants to login with the password LetM31n! and Adrian wants to login with the password M32Want_Access._

In our application a user logs in with a Username and not an E-mail. E-mail and Username are unique in our application. Currently there a Helge and a Adrian user in our application and they are created in our db initializer script, and they are created without a password. 

Essentially we need to figure out if we want to store a Helge and Adrian user with the requirements above. We need to take into account that helge probably will try to login in through github, if a user in our db has the same Username and or Email as the one on his github, he will not be allowed access. Also how do we interpret the: _'they should be able to do so using their email addresses (ropf@itu.dk and adho@itu.dk respectively). '_  - as we in our application has enforced login through Username and not E-mail.

**Comment by andsji** [comment]
We have decided as a group to not give the Helge & Adrian users passwords, as these would either have to be hard-coded in the DbInitializer script or manually added by us through the UI of the application. We felt both of these solutions were bad practice.
