### ISSUE TITLE
Session_03: 1.b) Automate certain project management tasks

### ISSUE THREAD

**Issue by Asger124** [ITU-BDSA2024-GROUP18/Chirp#18]
As a developer i want to use Github actions automate certain project management tasks, in order to create in order to streamline some trivial tasks

**Acceptance criteria:** 
- Choose at minimum two tasks(adding labels to issues, moving labels at state change i.e.) and automate them
- Test it to see that it works 

**Definition of done:**
- Ensure all acceptance criteria has been met 
- Sucesfully implment the changes and merge it with main branch

**Comment by andsji** [comment]
Actually in progress, but in Todo for testing purposes

**Comment by andsji** [comment]
Automation has been added through Git Actions instead of workflows due to issues. Unable to obtain help from TA's, who also said, that they had not heard of any group who had succeeded with adding automations through a workflow.
