### ISSUE TITLE
Session 04: 1.b) Refactor your Chirp! CLI client to use the CSV Database Web Service

### ISSUE THREAD

**Issue by Asger124** [ITU-BDSA2024-GROUP18/Chirp#45]
As a developer i want to refactor my client to use the CSV Database Web Service, such that the application eventually can be deployed on a web service and not only run locally. 

Acceptance criteria: 

- client shall now send HTTP GET and POST requests to the /cheeps and /cheep endpoint respectively.
- It shall not call the methods SimpleDB library project directly anymore.
- Adapt unit, integration and end-to-end tests so that they test the Chirp! application with its new architecture.
- [ ] The client application is manually deployable to Azure.

**Comment by Asger124** [comment]
I did not finish creating this issue because i was doubting whether it should be divided into several seperate ones

**Comment by andsji** [comment]
Reopened since our application is still not able to be deployed to Azure, but only works locally.
